env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - prettier
  - 'prettier/@typescript-eslint'
  - 'prettier/react'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  {
    'react/jsx-filename-extension':
      [2, { 'extensions': ['.js', '.jsx', '.ts', '.tsx'] }],
    'import/extensions':
      [
        'error',
        'ignorePackages',
        { 'js': 'never', 'jsx': 'never', 'ts': 'never', 'tsx': 'never' },
      ],
    'no-console': 'off',
  }
settings:
  {
    'import/resolver':
      { 'node': { 'extensions': ['.js', '.jsx', '.ts', '.tsx'] } },
  }
overrides:
  - {
      'files':
        [
          '**/*.spec.js',
          '**/*.spec.jsx',
          '**/*.spec.ts',
          '**/*.spec.tsx',
          '**/*.test.js',
          '**/*.test.jsx',
          '**/*.test.ts',
          '**/*.test.tsx',
        ],
      'env': { 'jest': true },
    }
